Synchronize Installation singleton's warHome setter because it resets propertyServiceMgr causing a potential for Toolkit homepage startup errors such as 'TkProps load failed.'
From the Tomcat log:

SEVERE: Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract gov.nist.toolkit.tk.client.TkProps gov.nist.toolkit.xdstools2.client.ToolkitService.getTkProps() throws gov.nist.toolkit.xdstools2.client.NoServletSessionException' threw an unexpected exception: java.lang.NullPointerException
 at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
 at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
 at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
 at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
 at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
 at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
 at org.apache.coyote.http11.Http11AprProcessor.process(Http11AprProcessor.java:879)
 at org.apache.coyote.http11.Http11AprProtocol$Http11ConnectionHandler.process(Http11AprProtocol.java:600)
 at org.apache.tomcat.util.net.AprEndpoint$Worker.run(AprEndpoint.java:1703)
 at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.NullPointerException
 at java.util.Hashtable.put(Hashtable.java:432)
 at java.util.Properties.setProperty(Properties.java:161)
 at java.lang.System.setProperty(System.java:785)
 at gov.nist.toolkit.installation.PropertyManager.getExternalCache(PropertyManager.java:110)
 at gov.nist.toolkit.session.server.Session.<init>(Session.java:171)
 at gov.nist.toolkit.session.server.Session.<init>(Session.java:162)
 at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.getSession(ToolkitServiceImpl.java:400)
 at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.getSession(ToolkitServiceImpl.java:358)
 at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.session(ToolkitServiceImpl.java:349)
 at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.getTkProps(ToolkitServiceImpl.java:214)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:601)
 at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
 ... 18 more

caused by first homeTab->...->getAdminPassword  and then async call to load tkProps->...->getExternalCache

--HG--
branch : bugfix/startup-gwt-error